
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

addons:
    postgresql: "9.4"

env:
    global:
        - CELERY_CONFIG='sqla+sqlite:///celerydb.sqlite'
        - CELERY_BACKEND_CONFIG='db+sqlite:///results.db'
before_install:
    - virtualenv ./pyenv --distribute
    - source ./pyenv/bin/activate
install:
    - python -m pip install -e .
    - python -m pip install psycopg2 pytest pytest-cov flask-testing coverage future futures
    - python -m pip install python-dateutil coveralls unicodecsv
    - python -m pip install git+git://github.com/okfn/tabulator-py.git
    - python -m pip install git+git://github.com/okfn/datapackage-py.git
before_script:
    - psql -c 'create database os;' -U postgres
    - python -m pytest --version
script:
    - python -m celery -A babbage_fiscal.tasks worker &
    - python -m coverage run --source babbage_fiscal -m pytest tests/
    - CELERY_ALWAYS_EAGER=true python -m coverage run --source babbage_fiscal -m pytest tests/
after_success:
    - coveralls
