
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

addons:
    postgresql: "9.4"

env:
    - FISCAL_PACKAGE_ENGINE=postgresql://postgres@/os
before_install:
    - virtualenv ./pyenv --distribute
    - source ./pyenv/bin/activate
install:
    - pip install -e .
    - pip install psycopg2 nose flask-testing coverage
    - pip install python-dateutil coveralls unicodecsv
before_script:
    - psql -c 'create database os;' -U postgres
    - nosetests --version
script:
    - nosetests --with-coverage --cover-package=babbage_fiscal
after_success:
    - coveralls